import {beforeEach,it,expect,vi} from 'vitest';
import {openTaskWizard} from './task-wizard';
import {parseBrief} from '../brief-parser';
beforeEach(()=>{document.body.replaceChildren();HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new Event('close'));};});
const button=(text:string)=>[...document.querySelectorAll<HTMLButtonElement>('button')].find(x=>x.textContent===text)!;
const input=(label:string,value:string)=>{const x=document.querySelector<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(`[aria-label="${label}"]`)!;x.value=value;x.dispatchEvent(new Event(x.tagName==='SELECT'?'change':'input'));};
async function fill(){input('手卡原文','品牌：唇本\n产品：唇蜜\n卖点：保湿\n达人要求：真实使用体验\n不要假装试用');button('解析手卡').click();button('下一步').click();button('美妆个护').click();button('下一步').click();input('达人类型','测评种草');input('出镜方式','real_person');button('下一步').click();input('任务名称','唇本真人测评');input('目标人数','1000');}
it('必须主动选类目并核对手卡，最终保存准确选择且不自动采集',async()=>{const create=vi.fn().mockResolvedValue({});openTaskWizard({onCreateTask:create});button('下一步').click();expect(document.querySelector('[role="alert"]')?.textContent).toContain('解析');await fill();button('保存任务').click();await vi.waitFor(()=>expect(create).toHaveBeenCalledOnce());const [name,count,s]=create.mock.calls[0];expect([name,count]).toEqual(['唇本真人测评',1000]);expect(s).toMatchObject({category:'美妆个护',creatorType:'测评种草',contentPresentation:'real_person',maximumFollowers:0,sourceDiscoveryMode:'structured_browse',keywords:[],brandName:'唇本',productName:'唇蜜',setupConfirmed:true});expect(s.brief).toContain('不要假装试用');expect(document.querySelector('dialog')).toBeNull();});
it('保存失败仍保留完整草稿，能够重试',async()=>{const create=vi.fn().mockRejectedValueOnce(new Error('作业尚未停止')).mockResolvedValueOnce({});openTaskWizard({onCreateTask:create});await fill();button('保存任务').click();await vi.waitFor(()=>expect(document.querySelector('[role="alert"]')?.textContent).toContain('作业尚未停止'));expect(document.querySelector('dialog')).toBeTruthy();expect((document.querySelector('[aria-label="任务名称"]') as HTMLInputElement).value).toBe('唇本真人测评');button('保存任务').click();await vi.waitFor(()=>expect(create).toHaveBeenCalledTimes(2));});
it('不把否定句或无标签内容猜成确定字段，也不擅改手卡类目',()=>{const p=parseBrief('不要求真人出镜\n产品名称：唇蜜\n类目：未知类目\n出镜方式：真人出镜');expect(p.fields.productName).toBe('唇蜜');expect(p.fields.category).toBeUndefined();expect(p.fields.contentPresentation).toBe('real_person');expect(p.unresolved).toEqual(['不要求真人出镜','类目：未知类目']);});

it('千问等待期间用户修改草稿，迟到的建议不得覆盖',async()=>{let resolve!:(v:any)=>void;const pending=new Promise<any>(r=>resolve=r);openTaskWizard({onUnderstandBrief:()=>pending});input('手卡原文','品牌：唇本');button('解析手卡').click();button('千问理解手卡').click();input('品牌','用户确认的品牌');resolve({fields:{brandName:'模型建议品牌'},sources:{},unresolved:[],provider:'qwen',model:'qwen-plus'});await vi.waitFor(()=>expect(document.querySelector('[role="alert"]')?.textContent).toContain('未覆盖'));expect((document.querySelector('[aria-label="品牌"]') as HTMLInputElement).value).toBe('用户确认的品牌');});

it('后续步骤可以直接取消且不会创建或运行任务',async()=>{const create=vi.fn();openTaskWizard({onCreateTask:create});await fill();button('取消').click();expect(document.querySelector('dialog')).toBeNull();expect(create).not.toHaveBeenCalled();});
it('千问读取失败仅显示用户可理解原因，原文和修改保留',async()=>{openTaskWizard({onUnderstandBrief:async()=>{throw new Error("Error invoking remote method 'aipr:understand-brief': Error: 没有读取到已有千问配置，尚未调用千问；未修改任何密钥");}});input('手卡原文','品牌：测试品牌');button('千问理解手卡').click();await vi.waitFor(()=>expect(document.querySelector('[role="alert"]')?.textContent).toContain('没有读取到已有千问配置'));expect(document.querySelector('[role="alert"]')?.textContent).not.toContain('remote method');expect((document.querySelector('[aria-label="手卡原文"]') as HTMLTextAreaElement).value).toBe('品牌：测试品牌');});
it('Esc在保存中被阻止，完成关闭清理弹窗',async()=>{let resolve!:()=>void;const pending=new Promise<void>(r=>resolve=r);openTaskWizard({onCreateTask:()=>pending});await fill();button('保存任务').click();const dialog=document.querySelector('dialog')!;const cancel=new Event('cancel',{cancelable:true});dialog.dispatchEvent(cancel);expect(cancel.defaultPrevented).toBe(true);resolve();await vi.waitFor(()=>expect(document.querySelector('dialog')).toBeNull());});
