import {readableError} from "../exclusive-action";
import {h} from "../store";
import type {CollectionStrategy} from "../types";
import {CATEGORIES,CREATOR_TYPES,PRESENTATIONS,parseBrief} from "../brief-parser";
export interface TaskWizardHandlers {onCreateTask?(name:string,count:number,strategy?:CollectionStrategy):void|Promise<void>;onReadBrief?():Promise<{text?:string}|null>;onUnderstandBrief?(text:string):Promise<{fields:Record<string,unknown>;sources:Record<string,string>;unresolved:string[];provider:string;model:string}>;}
export function openTaskWizard(handlers:TaskWizardHandlers):void {
 const dialog=document.createElement("dialog");dialog.className="task-wizard";
 let step=0,category="",creatorType="不限内容类型",presentation="any",name="",count=200,brief="",brand="",product="",selling="",criteria="",excluded="";let parsed=false;let busy=false;let draftRevision=0;let understanding=false;let interpretation="";let suggestions:Record<string,string[]>={};
 const body=h("div");dialog.append(body);document.body.append(dialog);
 dialog.addEventListener("close",()=>dialog.remove());
 dialog.addEventListener("cancel",event=>{if(busy)event.preventDefault();});
 const field=(label:string,value:string,change:(v:string)=>void,area=false)=>{const input=h(area?"textarea":"input",{"aria-label":label,value,maxLength:area?"20000":"2000"}) as HTMLInputElement|HTMLTextAreaElement;input.value=value;input.addEventListener("input",()=>{draftRevision++;change(input.value);});return h("label",{},[label,input]);};
 const select=(label:string,value:string,options:{value:string;label:string}[],change:(v:string)=>void)=>{const input=h("select",{"aria-label":label},options.map(x=>h("option",{value:x.value,text:x.label}))) as HTMLSelectElement;input.value=value;input.addEventListener("change",()=>{draftRevision++;change(input.value);});return h("label",{},[label,input]);};
 function render(){
  body.replaceChildren();const error=h("p",{role:"alert",class:"form-error"});
  body.append(h("h2",{text:"创建找达人任务"}),h("ol",{class:"wizard-steps"},["识别手卡","选类目","选达人","确认任务"].map((x,i)=>h("li",{class:i===step?"active":"",text:`${i+1}. ${x}`}))));
  if(step===1){body.append(h("h3",{text:"你要找哪个类目的达人？"}),h("p",{text:suggestions.category?.length?`AI建议：${suggestions.category.join("、")}；也可选择其他平台类目。`:"请选择平台类目。"}),h("div",{class:"category-cards"},CATEGORIES.map(x=>h("button",{type:"button",class:category===x?"selected":"","aria-pressed":String(category===x),text:x,onclick:()=>{category=x;render();}}))),h("p",{text:"按平台类目发现达人；作品是否适配产品，在后续审核中判断。"}));}
  if(step===2){body.append(h("h3",{text:"选择合作内容和出镜要求"}),...(suggestions.creatorType?.length?[h("p",{text:"AI建议的达人类型（也可自行填写）"}),h("div",{class:"category-cards"},suggestions.creatorType.map(value=>h("button",{type:"button",text:value,onclick:()=>{creatorType=value;render();}})))]:[]),select("达人类型",CREATOR_TYPES.includes(creatorType)?creatorType:"custom",[...CREATOR_TYPES.map(x=>({value:x,label:x})),{value:"custom",label:"没有符合的，自己填写"}],v=>{creatorType=v==="custom"?"":v;render();}),...(!CREATOR_TYPES.includes(creatorType)?[field("自定义达人类型",creatorType,v=>creatorType=v)]:[]),...(suggestions.contentPresentation?.length?[h("p",{text:"AI建议的出镜方式（由你选择确认）"}),h("div",{class:"category-cards"},suggestions.contentPresentation.map(value=>h("button",{type:"button",text:PRESENTATIONS.find(x=>x.value===value)?.label||value,onclick:()=>{presentation=value;render();}})))]:[]),select("出镜方式",presentation,PRESENTATIONS,v=>presentation=v),h("p",{text:"真人出镜必须有具体作品证据。仅有昵称、头像或标题时保留待复核。默认不限制粉丝量。"}));}
  if(step===0){
   body.append(h("h3",{text:"导入或粘贴品牌手卡"}),h("button",{type:"button",text:"选择手卡文件",onclick:async()=>{try{const r=await handlers.onReadBrief?.();if(r?.text){brief=r.text.slice(0,20000);parsed=false;render();}}catch(e){error.textContent=e instanceof Error?readableError(e.message):"导入失败";}}}),...(parsed?[h("details",{},[h("summary",{text:"查看或修改手卡原文"}),field("手卡原文",brief,v=>{brief=v;parsed=false;},true)])]:[field("手卡原文",brief,v=>{brief=v;parsed=false;},true)]));
   body.append(h("button",{type:"button",text:"解析手卡",onclick:()=>{if(!brief.trim()){error.textContent="请导入或填写品牌手卡";return;}const p=parseBrief(brief);brand=String(p.fields.brandName||brand);product=String(p.fields.productName||product);selling=String(p.fields.sellingPoints||selling);criteria=String(p.fields.criteria||criteria);excluded=p.fields.exclusions?.join("\n")||excluded;parsed=true;render();}}));
   body.append(h("button",{type:"button",text:"千问理解手卡",onclick:async()=>{if(!brief.trim()){error.textContent="请先填写手卡";return;}if(understanding)return;understanding=true;const source=brief;const revision=draftRevision;try{if(!handlers.onUnderstandBrief)throw Error("千问理解入口尚未连接");error.textContent="千问正在理解…";const result=await handlers.onUnderstandBrief(source);if(!dialog.isConnected)return;if(step!==0||brief!==source||revision!==draftRevision){error.textContent="草稿已修改，本次建议未覆盖你的内容，请重新理解";return;}brand=String(result.fields.brandName||brand);product=String(result.fields.productName||product);selling=String(result.fields.sellingPoints||selling);criteria=String(result.fields.criteria||criteria);if(Array.isArray(result.fields.exclusions))excluded=result.fields.exclusions.join("\n");suggestions=(result as {suggestions?:Record<string,string[]>}).suggestions||{};interpretation=`千问 ${result.model} 提出了草稿，尚未保存。${result.unresolved.length?"待确认："+result.unresolved.join("；"):"请核对全部条件。"}`;parsed=true;render();}catch(e){error.textContent=e instanceof Error?readableError(e.message):"理解失败，原文已保留";}finally{understanding=false;}}}));
   if(interpretation)body.append(h("p",{text:interpretation}));
   for(const [key,label,assign] of [["productName","产品",(v:string)=>product=v],["sellingPoints","卖点",(v:string)=>selling=v],["criteria","达人要求",(v:string)=>criteria=v]] as const){if(suggestions[key]?.length)body.append(h("h4",{text:`AI建议的${label}（可选，也可在下方自行输入）`}),h("div",{class:"category-cards"},suggestions[key].map(value=>h("button",{type:"button",text:value,onclick:()=>{assign(value);render();}}))));}

   if(parsed)body.append(h("p",{text:"已整理明确标注的字段，请核对并补充。自由文本仍保留为完整审核要求，类目和达人类型以你接下来的选择为准。"}),field("品牌",brand,v=>brand=v),field("产品",product,v=>product=v),field("核心卖点",selling,v=>selling=v,true),field("达人适配条件",criteria,v=>criteria=v,true),field("排除条件",excluded,v=>excluded=v,true));
  }
  if(step===3){body.append(h("h3",{text:"核对后保存任务"}),field("任务名称",name,v=>name=v),field("目标人数",String(count),v=>count=Number(v)),h("dl",{},[h("dt",{text:"类目 / 达人类型"}),h("dd",{text:`${category} / ${creatorType}`}),h("dt",{text:"出镜方式"}),h("dd",{text:PRESENTATIONS.find(x=>x.value===presentation)?.label||""}),h("dt",{text:"品牌 / 产品"}),h("dd",{text:`${brand||"未填"} / ${product||"未填"}`}),h("dt",{text:"适配条件"}),h("dd",{text:criteria||"按手卡原文审核"})]),h("p",{text:"按类目找，粉丝不限。有联系方式才进入正式名单；证据不足进入待复核。保存后由你点击开始，不自动采集或发消息。"}));}
  const back=h("button",{type:"button",text:step?"上一步":"取消",onclick:()=>{if(busy)return;if(!step){dialog.close();dialog.remove();}else{step--;render();}}});
  const next=h("button",{type:"button",class:"primary",disabled:busy,text:step===3?(busy?"正在保存…":"保存任务"):"下一步",onclick:async()=>{
   if(busy)return;if(step===1&&!category){error.textContent="请先选择类目";return;}
   if(step===0&&(!parsed||!brief.trim())){error.textContent="请先解析并核对品牌手卡";return;}
   if(step===2&&!creatorType.trim()){error.textContent="请选择或填写达人类型";return;}
   if(step<3){step++;if(step===3&&!name)name=`${brand||category} · 找达人`;render();return;}
   if(!name.trim()||!Number.isInteger(count)||count<1||count>5000){error.textContent="请填写任务名称和1–5000的整数人数";return;}
   busy=true;next.setAttribute("disabled","");try{await handlers.onCreateTask?.(name.trim(),count,{sourceType:"brief",category,creatorType,contentPresentation:presentation,brief,brandName:brand,productName:product,sellingPoints:selling,criteria,exclusions:excluded.split(/\n/).map(x=>x.trim()).filter(Boolean),targetCount:count,creatorLevels:[1,2,3,4],minimumFollowers:0,maximumFollowers:0,minimumMonthlySales:0,requireFemale:false,requireContact:true,activeShops:["A"],contentType:"短视频",sourceDiscoveryMode:"structured_browse",keywords:[],setupConfirmed:true});dialog.close();dialog.remove();}catch(e){error.textContent=e instanceof Error?readableError(e.message):"任务保存失败，填写内容已保留";}finally{busy=false;next.removeAttribute("disabled");}
  }});body.append(error,h("div",{class:"form-actions"},[
   ...(step?[h("button",{type:"button",text:"取消",disabled:busy,onclick:()=>{if(!busy)dialog.close();}})]:[]),back,next]));
 }
 render();dialog.showModal();
}
